// ignore_for_file: camel_case_types, non_constant_identifier_names, constant_identifier_names, prefer_expression_function_bodies, public_member_api_docs

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:everything_search_engine/src/ffi/everything.g.dart')
library;

import 'dart:ffi' as ffi;

/// write search state
@ffi.Native<ffi.Void Function(LPCWSTR)>(symbol: 'Everything_SetSearchW')
external void SetSearchW(LPCWSTR lpString);

@ffi.Native<ffi.Void Function(LPCSTR)>(symbol: 'Everything_SetSearchA')
external void SetSearchA(LPCSTR lpString);

@ffi.Native<ffi.Void Function(BOOL)>(symbol: 'Everything_SetMatchPath')
external void SetMatchPath(int bEnable);

@ffi.Native<ffi.Void Function(BOOL)>(symbol: 'Everything_SetMatchCase')
external void SetMatchCase(int bEnable);

@ffi.Native<ffi.Void Function(BOOL)>(symbol: 'Everything_SetMatchWholeWord')
external void SetMatchWholeWord(int bEnable);

@ffi.Native<ffi.Void Function(BOOL)>(symbol: 'Everything_SetRegex')
external void SetRegex(int bEnable);

@ffi.Native<ffi.Void Function(DWORD)>(symbol: 'Everything_SetMax')
external void SetMax(int dwMax);

@ffi.Native<ffi.Void Function(DWORD)>(symbol: 'Everything_SetOffset')
external void SetOffset(int dwOffset);

@ffi.Native<ffi.Void Function(HWND)>(symbol: 'Everything_SetReplyWindow')
external void SetReplyWindow(HWND hWnd);

@ffi.Native<ffi.Void Function(DWORD)>(symbol: 'Everything_SetReplyID')
external void SetReplyID(int dwId);

@ffi.Native<ffi.Void Function(DWORD)>(symbol: 'Everything_SetSort')
external void SetSort(int dwSort);

@ffi.Native<ffi.Void Function(DWORD)>(symbol: 'Everything_SetRequestFlags')
external void SetRequestFlags(int dwRequestFlags);

/// read search state
@ffi.Native<BOOL Function()>(symbol: 'Everything_GetMatchPath')
external int GetMatchPath();

@ffi.Native<BOOL Function()>(symbol: 'Everything_GetMatchCase')
external int GetMatchCase();

@ffi.Native<BOOL Function()>(symbol: 'Everything_GetMatchWholeWord')
external int GetMatchWholeWord();

@ffi.Native<BOOL Function()>(symbol: 'Everything_GetRegex')
external int GetRegex();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetMax')
external int GetMax();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetOffset')
external int GetOffset();

@ffi.Native<LPCSTR Function()>(symbol: 'Everything_GetSearchA')
external LPCSTR GetSearchA();

@ffi.Native<LPCWSTR Function()>(symbol: 'Everything_GetSearchW')
external LPCWSTR GetSearchW();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetLastError')
external int GetLastError();

@ffi.Native<HWND Function()>(symbol: 'Everything_GetReplyWindow')
external HWND GetReplyWindow();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetReplyID')
external int GetReplyID();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetSort')
external int GetSort();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetRequestFlags')
external int GetRequestFlags();

/// execute query
@ffi.Native<BOOL Function(BOOL)>(symbol: 'Everything_QueryA')
external int QueryA(int bWait);

@ffi.Native<BOOL Function(BOOL)>(symbol: 'Everything_QueryW')
external int QueryW(int bWait);

/// query reply
@ffi.Native<BOOL Function(UINT, WPARAM, LPARAM, DWORD)>(
  symbol: 'Everything_IsQueryReply',
)
external int IsQueryReply(int message, int wParam, int lParam, int dwId);

/// write result state
@ffi.Native<ffi.Void Function()>(symbol: 'Everything_SortResultsByPath')
external void SortResultsByPath();

/// read result state
@ffi.Native<DWORD Function()>(symbol: 'Everything_GetNumFileResults')
external int GetNumFileResults();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetNumFolderResults')
external int GetNumFolderResults();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetNumResults')
external int GetNumResults();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetTotFileResults')
external int GetTotFileResults();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetTotFolderResults')
external int GetTotFolderResults();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetTotResults')
external int GetTotResults();

@ffi.Native<BOOL Function(DWORD)>(symbol: 'Everything_IsVolumeResult')
external int IsVolumeResult(int dwIndex);

@ffi.Native<BOOL Function(DWORD)>(symbol: 'Everything_IsFolderResult')
external int IsFolderResult(int dwIndex);

@ffi.Native<BOOL Function(DWORD)>(symbol: 'Everything_IsFileResult')
external int IsFileResult(int dwIndex);

@ffi.Native<LPCWSTR Function(DWORD)>(symbol: 'Everything_GetResultFileNameW')
external LPCWSTR GetResultFileNameW(int dwIndex);

@ffi.Native<LPCSTR Function(DWORD)>(symbol: 'Everything_GetResultFileNameA')
external LPCSTR GetResultFileNameA(int dwIndex);

@ffi.Native<LPCWSTR Function(DWORD)>(symbol: 'Everything_GetResultPathW')
external LPCWSTR GetResultPathW(int dwIndex);

@ffi.Native<LPCSTR Function(DWORD)>(symbol: 'Everything_GetResultPathA')
external LPCSTR GetResultPathA(int dwIndex);

@ffi.Native<DWORD Function(DWORD, LPSTR, DWORD)>(
  symbol: 'Everything_GetResultFullPathNameA',
)
external int GetResultFullPathNameA(int dwIndex, LPSTR buf, int bufsize);

@ffi.Native<DWORD Function(DWORD, LPWSTR, DWORD)>(
  symbol: 'Everything_GetResultFullPathNameW',
)
external int GetResultFullPathNameW(
  int dwIndex,
  LPWSTR wbuf,
  int wbuf_size_in_wchars,
);

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetResultListSort')
external int GetResultListSort();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetResultListRequestFlags')
external int GetResultListRequestFlags();

@ffi.Native<LPCWSTR Function(DWORD)>(symbol: 'Everything_GetResultExtensionW')
external LPCWSTR GetResultExtensionW(int dwIndex);

@ffi.Native<LPCSTR Function(DWORD)>(symbol: 'Everything_GetResultExtensionA')
external LPCSTR GetResultExtensionA(int dwIndex);

@ffi.Native<BOOL Function(DWORD, ffi.Pointer<LARGE_INTEGER>)>(
  symbol: 'Everything_GetResultSize',
)
external int GetResultSize(int dwIndex, ffi.Pointer<LARGE_INTEGER> lpSize);

@ffi.Native<BOOL Function(DWORD, ffi.Pointer<FILETIME>)>(
  symbol: 'Everything_GetResultDateCreated',
)
external int GetResultDateCreated(
  int dwIndex,
  ffi.Pointer<FILETIME> lpDateCreated,
);

@ffi.Native<BOOL Function(DWORD, ffi.Pointer<FILETIME>)>(
  symbol: 'Everything_GetResultDateModified',
)
external int GetResultDateModified(
  int dwIndex,
  ffi.Pointer<FILETIME> lpDateModified,
);

@ffi.Native<BOOL Function(DWORD, ffi.Pointer<FILETIME>)>(
  symbol: 'Everything_GetResultDateAccessed',
)
external int GetResultDateAccessed(
  int dwIndex,
  ffi.Pointer<FILETIME> lpDateAccessed,
);

@ffi.Native<DWORD Function(DWORD)>(symbol: 'Everything_GetResultAttributes')
external int GetResultAttributes(int dwIndex);

@ffi.Native<LPCWSTR Function(DWORD)>(
  symbol: 'Everything_GetResultFileListFileNameW',
)
external LPCWSTR GetResultFileListFileNameW(int dwIndex);

@ffi.Native<LPCSTR Function(DWORD)>(
  symbol: 'Everything_GetResultFileListFileNameA',
)
external LPCSTR GetResultFileListFileNameA(int dwIndex);

@ffi.Native<DWORD Function(DWORD)>(symbol: 'Everything_GetResultRunCount')
external int GetResultRunCount(int dwIndex);

@ffi.Native<BOOL Function(DWORD, ffi.Pointer<FILETIME>)>(
  symbol: 'Everything_GetResultDateRun',
)
external int GetResultDateRun(int dwIndex, ffi.Pointer<FILETIME> lpDateRun);

@ffi.Native<BOOL Function(DWORD, ffi.Pointer<FILETIME>)>(
  symbol: 'Everything_GetResultDateRecentlyChanged',
)
external int GetResultDateRecentlyChanged(
  int dwIndex,
  ffi.Pointer<FILETIME> lpDateRecentlyChanged,
);

@ffi.Native<LPCWSTR Function(DWORD)>(
  symbol: 'Everything_GetResultHighlightedFileNameW',
)
external LPCWSTR GetResultHighlightedFileNameW(int dwIndex);

@ffi.Native<LPCSTR Function(DWORD)>(
  symbol: 'Everything_GetResultHighlightedFileNameA',
)
external LPCSTR GetResultHighlightedFileNameA(int dwIndex);

@ffi.Native<LPCWSTR Function(DWORD)>(
  symbol: 'Everything_GetResultHighlightedPathW',
)
external LPCWSTR GetResultHighlightedPathW(int dwIndex);

@ffi.Native<LPCSTR Function(DWORD)>(
  symbol: 'Everything_GetResultHighlightedPathA',
)
external LPCSTR GetResultHighlightedPathA(int dwIndex);

@ffi.Native<LPCWSTR Function(DWORD)>(
  symbol: 'Everything_GetResultHighlightedFullPathAndFileNameW',
)
external LPCWSTR GetResultHighlightedFullPathAndFileNameW(int dwIndex);

@ffi.Native<LPCSTR Function(DWORD)>(
  symbol: 'Everything_GetResultHighlightedFullPathAndFileNameA',
)
external LPCSTR GetResultHighlightedFullPathAndFileNameA(int dwIndex);

/// reset state and free any allocated memory
@ffi.Native<ffi.Void Function()>(symbol: 'Everything_Reset')
external void Reset();

@ffi.Native<ffi.Void Function()>(symbol: 'Everything_CleanUp')
external void CleanUp();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetMajorVersion')
external int GetMajorVersion();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetMinorVersion')
external int GetMinorVersion();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetRevision')
external int GetRevision();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetBuildNumber')
external int GetBuildNumber();

@ffi.Native<BOOL Function()>(symbol: 'Everything_Exit')
external int Exit();

@ffi.Native<UINT Function(ffi.Pointer<ffi.Void>)>(
  symbol: 'Everything_MSIExitAndStopService',
)
external int MSIExitAndStopService(ffi.Pointer<ffi.Void> msihandle);

@ffi.Native<UINT Function(ffi.Pointer<ffi.Void>)>(
  symbol: 'Everything_MSIStartService',
)
external int MSIStartService(ffi.Pointer<ffi.Void> msihandle);

@ffi.Native<BOOL Function()>(symbol: 'Everything_IsDBLoaded')
external int IsDBLoaded();

@ffi.Native<BOOL Function()>(symbol: 'Everything_IsAdmin')
external int IsAdmin();

@ffi.Native<BOOL Function()>(symbol: 'Everything_IsAppData')
external int IsAppData();

@ffi.Native<BOOL Function()>(symbol: 'Everything_RebuildDB')
external int RebuildDB();

@ffi.Native<BOOL Function()>(symbol: 'Everything_UpdateAllFolderIndexes')
external int UpdateAllFolderIndexes();

@ffi.Native<BOOL Function()>(symbol: 'Everything_SaveDB')
external int SaveDB();

@ffi.Native<BOOL Function()>(symbol: 'Everything_SaveRunHistory')
external int SaveRunHistory();

@ffi.Native<BOOL Function()>(symbol: 'Everything_DeleteRunHistory')
external int DeleteRunHistory();

@ffi.Native<DWORD Function()>(symbol: 'Everything_GetTargetMachine')
external int GetTargetMachine();

@ffi.Native<BOOL Function(DWORD)>(symbol: 'Everything_IsFastSort')
external int IsFastSort(int sortType);

@ffi.Native<BOOL Function(DWORD)>(symbol: 'Everything_IsFileInfoIndexed')
external int IsFileInfoIndexed(int fileInfoType);

@ffi.Native<DWORD Function(LPCWSTR)>(
  symbol: 'Everything_GetRunCountFromFileNameW',
)
external int GetRunCountFromFileNameW(LPCWSTR lpFileName);

@ffi.Native<DWORD Function(LPCSTR)>(
  symbol: 'Everything_GetRunCountFromFileNameA',
)
external int GetRunCountFromFileNameA(LPCSTR lpFileName);

@ffi.Native<BOOL Function(LPCWSTR, DWORD)>(
  symbol: 'Everything_SetRunCountFromFileNameW',
)
external int SetRunCountFromFileNameW(LPCWSTR lpFileName, int dwRunCount);

@ffi.Native<BOOL Function(LPCSTR, DWORD)>(
  symbol: 'Everything_SetRunCountFromFileNameA',
)
external int SetRunCountFromFileNameA(LPCSTR lpFileName, int dwRunCount);

@ffi.Native<DWORD Function(LPCWSTR)>(
  symbol: 'Everything_IncRunCountFromFileNameW',
)
external int IncRunCountFromFileNameW(LPCWSTR lpFileName);

@ffi.Native<DWORD Function(LPCSTR)>(
  symbol: 'Everything_IncRunCountFromFileNameA',
)
external int IncRunCountFromFileNameA(LPCSTR lpFileName);

typedef WCHAR = ffi.WChar;
typedef DartWCHAR = int;
typedef LPCWSTR = ffi.Pointer<WCHAR>;
typedef CHAR = ffi.Char;
typedef DartCHAR = int;
typedef LPCSTR = ffi.Pointer<CHAR>;
typedef BOOL = ffi.Int;
typedef DartBOOL = int;
typedef DWORD = ffi.UnsignedLong;
typedef DartDWORD = int;

final class HWND__ extends ffi.Struct {
  @ffi.Int()
  external int unused;
}

typedef HWND = ffi.Pointer<HWND__>;
typedef UINT = ffi.UnsignedInt;
typedef DartUINT = int;
typedef UINT_PTR = ffi.UnsignedLongLong;
typedef DartUINT_PTR = int;
typedef WPARAM = UINT_PTR;
typedef LONG_PTR = ffi.LongLong;
typedef DartLONG_PTR = int;
typedef LPARAM = LONG_PTR;
typedef LPSTR = ffi.Pointer<CHAR>;
typedef LPWSTR = ffi.Pointer<WCHAR>;
typedef LONG = ffi.Long;
typedef DartLONG = int;

final class UnnamedStruct extends ffi.Struct {
  @DWORD()
  external int LowPart;

  @LONG()
  external int HighPart;
}

final class UnnamedStruct$1 extends ffi.Struct {
  @DWORD()
  external int LowPart;

  @LONG()
  external int HighPart;
}

typedef LONGLONG = ffi.LongLong;
typedef DartLONGLONG = int;

final class _LARGE_INTEGER extends ffi.Union {
  external UnnamedStruct unnamed;

  external UnnamedStruct$1 u;

  @LONGLONG()
  external int QuadPart;
}

typedef LARGE_INTEGER = _LARGE_INTEGER;

final class _FILETIME extends ffi.Struct {
  @DWORD()
  external int dwLowDateTime;

  @DWORD()
  external int dwHighDateTime;
}

typedef FILETIME = _FILETIME;

const int EVERYTHING_SDK_VERSION = 2;

const int EVERYTHING_OK = 0;

const int EVERYTHING_ERROR_MEMORY = 1;

const int EVERYTHING_ERROR_IPC = 2;

const int EVERYTHING_ERROR_REGISTERCLASSEX = 3;

const int EVERYTHING_ERROR_CREATEWINDOW = 4;

const int EVERYTHING_ERROR_CREATETHREAD = 5;

const int EVERYTHING_ERROR_INVALIDINDEX = 6;

const int EVERYTHING_ERROR_INVALIDCALL = 7;

const int EVERYTHING_ERROR_INVALIDREQUEST = 8;

const int EVERYTHING_ERROR_INVALIDPARAMETER = 9;

const int EVERYTHING_SORT_NAME_ASCENDING = 1;

const int EVERYTHING_SORT_NAME_DESCENDING = 2;

const int EVERYTHING_SORT_PATH_ASCENDING = 3;

const int EVERYTHING_SORT_PATH_DESCENDING = 4;

const int EVERYTHING_SORT_SIZE_ASCENDING = 5;

const int EVERYTHING_SORT_SIZE_DESCENDING = 6;

const int EVERYTHING_SORT_EXTENSION_ASCENDING = 7;

const int EVERYTHING_SORT_EXTENSION_DESCENDING = 8;

const int EVERYTHING_SORT_TYPE_NAME_ASCENDING = 9;

const int EVERYTHING_SORT_TYPE_NAME_DESCENDING = 10;

const int EVERYTHING_SORT_DATE_CREATED_ASCENDING = 11;

const int EVERYTHING_SORT_DATE_CREATED_DESCENDING = 12;

const int EVERYTHING_SORT_DATE_MODIFIED_ASCENDING = 13;

const int EVERYTHING_SORT_DATE_MODIFIED_DESCENDING = 14;

const int EVERYTHING_SORT_ATTRIBUTES_ASCENDING = 15;

const int EVERYTHING_SORT_ATTRIBUTES_DESCENDING = 16;

const int EVERYTHING_SORT_FILE_LIST_FILENAME_ASCENDING = 17;

const int EVERYTHING_SORT_FILE_LIST_FILENAME_DESCENDING = 18;

const int EVERYTHING_SORT_RUN_COUNT_ASCENDING = 19;

const int EVERYTHING_SORT_RUN_COUNT_DESCENDING = 20;

const int EVERYTHING_SORT_DATE_RECENTLY_CHANGED_ASCENDING = 21;

const int EVERYTHING_SORT_DATE_RECENTLY_CHANGED_DESCENDING = 22;

const int EVERYTHING_SORT_DATE_ACCESSED_ASCENDING = 23;

const int EVERYTHING_SORT_DATE_ACCESSED_DESCENDING = 24;

const int EVERYTHING_SORT_DATE_RUN_ASCENDING = 25;

const int EVERYTHING_SORT_DATE_RUN_DESCENDING = 26;

const int EVERYTHING_REQUEST_FILE_NAME = 1;

const int EVERYTHING_REQUEST_PATH = 2;

const int EVERYTHING_REQUEST_FULL_PATH_AND_FILE_NAME = 4;

const int EVERYTHING_REQUEST_EXTENSION = 8;

const int EVERYTHING_REQUEST_SIZE = 16;

const int EVERYTHING_REQUEST_DATE_CREATED = 32;

const int EVERYTHING_REQUEST_DATE_MODIFIED = 64;

const int EVERYTHING_REQUEST_DATE_ACCESSED = 128;

const int EVERYTHING_REQUEST_ATTRIBUTES = 256;

const int EVERYTHING_REQUEST_FILE_LIST_FILE_NAME = 512;

const int EVERYTHING_REQUEST_RUN_COUNT = 1024;

const int EVERYTHING_REQUEST_DATE_RUN = 2048;

const int EVERYTHING_REQUEST_DATE_RECENTLY_CHANGED = 4096;

const int EVERYTHING_REQUEST_HIGHLIGHTED_FILE_NAME = 8192;

const int EVERYTHING_REQUEST_HIGHLIGHTED_PATH = 16384;

const int EVERYTHING_REQUEST_HIGHLIGHTED_FULL_PATH_AND_FILE_NAME = 32768;

const int EVERYTHING_TARGET_MACHINE_X86 = 1;

const int EVERYTHING_TARGET_MACHINE_X64 = 2;

const int EVERYTHING_TARGET_MACHINE_ARM = 3;
