// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'everything_search_engine';

  static const String Everything64_dll = 'thirdparty/dll/Everything64.dll';
  static const String everything_search_engine$Everything64_dll = 'packages/everything_search_engine/thirdparty/dll/Everything64.dll';
}
